// grepnavi_path: 2つの関数の間の呼び出し経路を1往復で返す。
//
// depth 付きの callers/callees は部分木を丸ごと返すため、経路1本を知りたいだけでも
// 数百件ぶんのトークンを払うことになる。探索をブリッジ側で完結させ、返すのは
// 経路そのものだけに絞る。
//
// 探索は双方向。上（to から callers）だけで辿ると kmalloc のような多用される関数で
// 分岐が爆発するが、下（from から callees）は関数の長さで頭打ちになる。
// 毎回小さい方のフロンティアを伸ばして中間で出会わせる。
import { client, ok } from "../shared.js";
import type { ToolDef, ToolHandler } from "../shared.js";
import { normalizeInputPath } from "../helpers.js";

const DEFAULT_MAX_DEPTH = 4;
const MAX_MAX_DEPTH = 6;
const FANOUT_CAP = 60; // 1関数あたりに辿る呼び出し元の上限
const CALLEE_FANOUT_CAP = 30; // 同、呼び出し先
const VISIT_BUDGET = 400;
// 実時間の上限。1照会あたり数百ms かかるため、ノード数の上限だけでは待たされ過ぎる。
const TIME_BUDGET_MS = 20_000;

interface Edge {
  peer: string; // 経路上の隣（前進側は呼ばれる側、後退側も呼ばれる側）
  file?: string; // 呼び出しが書かれているファイル
  call_line?: number;
  text?: string;
}

interface Step {
  func: string;
  file?: string;
  call_line?: number;
  text?: string;
}

export const definitions: ToolDef[] = [
  {
    name: "grepnavi_path",
    description:
      "Find a call path from one function to another and return ONLY that path.\n\n" +
      "Prefer this over `grepnavi_callers(depth: N)` when the question is \"how does A reach B\": a depth-N walk returns the whole subtree (hundreds of entries you pay tokens for), while this returns the chain alone.\n\n" +
      "Searches from both ends at once (callees down from `from`, callers up from `to`), so a widely-called target like a memory allocator no longer blows up the search.\n\n" +
      "Accuracy follows the call engines: comment-only mentions and `#if 0` blocks are excluded, but calls made through function pointers or generated by macros are invisible — `found: false` means \"no direct chain seen\", not \"unreachable\". Every hop carries `text` (the call line source) so you can verify the chain yourself.\n\n" +
      "Returns `{ found, path: [{ func, file, call_line, text }], hops, visited, truncated }`. `path[0]` is `from`, the last entry is `to`. When `found` is false, `truncated` tells you whether the budget ran out (a path may still exist) or the search was exhaustive.\n\n" +
      "**Next step**: pin the chain with grepnavi_graph_add_nodes, or grepnavi_func_body on any hop you need to read.",
    inputSchema: {
      type: "object",
      properties: {
        from: { type: "string", description: "Function the path should start at (the outer caller)." },
        to: { type: "string", description: "Function the path should end at (the callee being reached)." },
        max_depth: {
          type: "integer",
          description: `Maximum hops between the two (default ${DEFAULT_MAX_DEPTH}, max ${MAX_MAX_DEPTH}).`,
        },
        dir: { type: "string", description: "Optional subdirectory to limit the search." },
      },
      required: ["from", "to"],
    },
  },
];

export const handlers: Record<string, ToolHandler> = {
  grepnavi_path: async (args) => {
    const a = args as { from: string; to: string; max_depth?: number; dir?: string };
    if (!a.from || !a.to) throw new Error("`from` and `to` are both required");
    const maxDepth = Math.min(Math.max(a.max_depth ?? DEFAULT_MAX_DEPTH, 1), MAX_MAX_DEPTH);
    const dir = normalizeInputPath(a.dir);

    if (a.from === a.to) {
      return ok({ found: true, path: [{ func: a.from }], hops: 0, visited: 0, truncated: false });
    }

    // down: 呼ばれる側へ辿った記録（親 -> 子）、up: 呼び出し元へ辿った記録（子の呼び出し元 -> 子）
    const down = new Map<string, Edge>();
    const up = new Map<string, Edge>();
    const seenDown = new Set<string>([a.from]);
    const seenUp = new Set<string>([a.to]);
    let frontDown = [a.from];
    let frontUp = [a.to];

    const state = { visited: 0, truncated: false, deadline: Date.now() + TIME_BUDGET_MS };
    const budgetLeft = () => state.visited < VISIT_BUDGET && Date.now() < state.deadline;

    for (let hops = 1; hops <= maxDepth; hops++) {
      if (frontDown.length === 0 && frontUp.length === 0) break;
      if (!budgetLeft()) {
        state.truncated = true;
        break;
      }
      // 小さい方を伸ばす（両端の分岐数の積ではなく和に抑える）
      const goDown =
        frontDown.length > 0 && (frontUp.length === 0 || frontDown.length <= frontUp.length);

      if (goDown) {
        const next: string[] = [];
        for (const name of frontDown) {
          if (!budgetLeft()) {
            state.truncated = true;
            break;
          }
          state.visited++;
          for (const e of await expandDown(name, dir, state)) {
            if (seenDown.has(e.peer)) continue;
            seenDown.add(e.peer);
            down.set(e.peer, { peer: name, file: e.file, call_line: e.call_line, text: e.text });
            if (seenUp.has(e.peer)) {
              return ok(join(a.from, a.to, e.peer, down, up, state));
            }
            next.push(e.peer);
          }
        }
        frontDown = next;
      } else {
        const next: string[] = [];
        for (const name of frontUp) {
          if (!budgetLeft()) {
            state.truncated = true;
            break;
          }
          state.visited++;
          let sites;
          try {
            const res = await client.callersWithMeta(name, { dir });
            sites = res.sites;
            // 呼び出し元一覧そのものが上限で切られていたら、経路が無いとは言い切れない
            if (res.truncated) state.truncated = true;
          } catch {
            continue; // 1関数の失敗で探索全体を止めない
          }
          if (sites.length > FANOUT_CAP) state.truncated = true;
          for (const s of sites.slice(0, FANOUT_CAP)) {
            if (seenUp.has(s.func)) continue;
            seenUp.add(s.func);
            up.set(s.func, {
              peer: name,
              file: s.file,
              call_line: s.call_line,
              text: (s as { text?: string }).text,
            });
            if (seenDown.has(s.func)) {
              return ok(join(a.from, a.to, s.func, down, up, state));
            }
            next.push(s.func);
          }
        }
        frontUp = next;
      }
    }

    return ok({
      found: false,
      path: [],
      hops: maxDepth,
      visited: state.visited,
      truncated: state.truncated,
      hint: state.truncated
        ? "Search hit its budget before exhausting the graph, so a path may still exist. Scope it with `dir`, or raise `max_depth` if the two are far apart."
        : "No direct call chain within max_depth. Calls through function pointers or macros are invisible to a text-based engine.",
    });
  },
};

// expandDown は name が呼んでいる関数を1段ぶん返す。
// 定義解決が要るぶん callers より高コストなので、関数と分かるものだけを辿る
// （マクロや構造体メンバを追いかけても呼び出し経路にはならない）。
async function expandDown(
  name: string,
  dir: string | undefined,
  state: { truncated: boolean },
): Promise<Edge[]> {
  let def;
  try {
    const r = await client.definition(name, { dir });
    def = r.hits.find((h) => h.kind === "func") ?? r.hits[0];
  } catch {
    return [];
  }
  if (!def) return [];
  let hits;
  try {
    hits = await client.callees(def.file, def.line);
  } catch {
    return [];
  }
  if (hits.length > CALLEE_FANOUT_CAP) state.truncated = true;
  return hits.slice(0, CALLEE_FANOUT_CAP).map((h) => ({
    peer: h.name,
    file: def.file,
    call_line: h.call_line,
    text: (h as { text?: string }).text,
  }));
}

// join は出会った地点から両側を復元して from -> to の一本道にする。
function join(
  from: string,
  to: string,
  meet: string,
  down: Map<string, Edge>,
  up: Map<string, Edge>,
  state: { visited: number; truncated: boolean },
) {
  // meet から from 側へ遡り、各ノードが「次を呼ぶ位置」を持つ形に組み替える
  const head: Step[] = [];
  let cur = meet;
  while (cur !== from) {
    const e = down.get(cur);
    if (!e) break;
    head.unshift({ func: e.peer, file: e.file, call_line: e.call_line, text: e.text });
    cur = e.peer;
  }
  const tail: Step[] = [];
  cur = meet;
  while (cur !== to) {
    const e = up.get(cur);
    if (!e) break;
    tail.push({ func: cur, file: e.file, call_line: e.call_line, text: e.text });
    cur = e.peer;
  }
  // head は from..meet の手前、tail は meet..to の手前までを持つ。
  // 終点はどちらにも含まれないので最後に1回だけ足す（meet === to でも重複しない）。
  const path = [...head, ...tail, { func: to }];
  return { found: true, path, hops: path.length - 1, visited: state.visited, truncated: state.truncated };
}
